import { useDialogFocus } from '../../shell/useDialogFocus';
import { useRef, useState } from 'react';
import { listFlows, getFlowDetail } from '../../bridge/mockBridge';
import type { Flow, FlowDetail } from '../../domain/types';
import { exportHar, parseHar, readPreviewSessions, sessionsKey, snapshot, type PreviewSession } from './sessionFiles';
export function SessionManager({ flows, details, onLoad, onClose }: { flows: Flow[]; details: Record<number, FlowDetail>; onLoad: (session: PreviewSession) => void; onClose: () => void }) {
  const dialogRoot=useRef<HTMLDivElement>(null); useDialogFocus(dialogRoot,onClose);
  const [sessions, setSessions] = useState(readPreviewSessions); const [name,setName] = useState(''); const [text,setText] = useState(''); const [preview,setPreview] = useState<PreviewSession | null>(null); const [error,setError] = useState('');
  function write(next: PreviewSession[]) { localStorage.setItem(sessionsKey,JSON.stringify(next)); setSessions(next); window.dispatchEvent(new Event('traffic-studio-sessions-change')); }
  return <div className="settings-backdrop"><div ref={dialogRoot} className="layout-manager" role="dialog" aria-modal="true" aria-label="Session and HAR preview"><h2>Sessions & HAR</h2><p>Local preview data, never live capture. Credential headers are removed; inspect body and URLs before saving/exporting.</p><label>Session name<input aria-label="Session name" value={name} onChange={e => setName(e.target.value)}/></label><button disabled={!name.trim()} onClick={() => { try { write([...sessions,snapshot(name.trim(),flows,details)]); setName(''); setError('Saved preview session in this browser.'); } catch { setError('Storage unavailable or full. Export the HAR text instead.'); } }}>Save current preview</button>{sessions.map(s => <div className="named-layout" key={s.id}><strong>{s.name} · {s.flows.length} flows</strong><button onClick={() => { onLoad(s); onClose(); }}>Open</button></div>)}<h3>Performance fixture</h3><button onClick={()=>{const base=listFlows();const details:Record<number,FlowDetail>={};const flows=Array.from({length:10000},(_,i)=>{const f=base[i%base.length];const id=i+1;const d=getFlowDetail(f.id);if(d)details[id]={...d,id};return {...f,id};});onLoad({id:'performance-sample',name:'10,000 synthetic sample rows',created:new Date().toISOString(),flows,details});onClose();}}>Load 10,000 sample rows</button><h3>Import / export HAR</h3><input type="file" aria-label="Read HAR file" accept=".har,.json,application/json" onChange={async e => { const file=e.target.files?.[0]; if(file) { if(file.size>20*1024*1024) { setError('HAR file exceeds 20 MB preview limit.'); return; } setText(await file.text()); setPreview(null); } }}/><textarea aria-label="HAR JSON" style={{width:'100%',height:150,background:'#303030',color:'#ddd'}} value={text} onChange={e => {setText(e.target.value);setPreview(null);}}/><button onClick={() => {try { setPreview(parseHar(text));setError('');} catch(e) {setPreview(null);setError(e instanceof Error ? e.message : 'Invalid HAR');}}}>Validate HAR</button><button onClick={() => {setText(exportHar(flows,details));setPreview(null);}}>Prepare HAR export</button><button disabled={!text} onClick={() => {const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='traffic-studio-preview.har';a.click();window.setTimeout(() => URL.revokeObjectURL(url),1000);}}>Download JSON</button>{preview && <p>{preview.flows.length} entries validated. <button onClick={() => {onLoad(preview);onClose();}}>Open imported preview</button></p>}<p role="status">{error}</p><button onClick={onClose}>Close</button></div></div>;
}
