use super::*;
use std::collections::HashSet;
#[derive(Serialize)]
#[serde(rename_all="camelCase")]
pub struct RetentionResult{pub body_references:usize,pub files:usize,pub bytes:u64}
impl Database{
 pub fn retain(&self,workspace:&str,days:u32,apply:bool)->ApiResult<RetentionResult>{
  if !(1..=3650).contains(&days){return Err(ApiError::new("validation","Unused body age must be 1–3650 days."));}let _content=crate::platform::content_lock::ContentLock::enter(&self.root)?;let mut connection=self.lock()?;Self::require_workspace(&connection,workspace)?;let tx=connection.transaction_with_behavior(TransactionBehavior::Immediate)?;
  let active:bool=tx.query_row("SELECT EXISTS(SELECT 1 FROM entities WHERE workspace_id=?1 AND json_extract(payload,'$.state') IN ('running','starting','recording','connecting','connected'))",[workspace],|r|r.get(0))?;if active{return Err(ApiError::new("busy","Stop native capture/streams and finish HTTP runs before retention."));}
  let mut used=HashSet::new();{let mut statement=tx.prepare("SELECT payload FROM entities WHERE workspace_id=?1")?;let rows=statement.query_map([workspace],|r|r.get::<_,String>(0))?;for row in rows{collect(&serde_json::from_str::<Value>(&row?)?,&mut used);}}
  let cutoff=now()-days as i64*86400000;let candidates={let mut statement=tx.prepare("SELECT id,sha256,size FROM blobs WHERE workspace_id=?1 AND created_at<?2")?;let rows=statement.query_map(params![workspace,cutoff],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?)))?;rows.collect::<Result<Vec<_>,_>>()?.into_iter().filter(|(id,_,_)|!used.contains(id)).collect::<Vec<_>>()};
  let mut result=RetentionResult{body_references:candidates.len(),files:0,bytes:0};let hashes=candidates.iter().map(|(_,hash,_)|hash.clone()).collect::<HashSet<_>>();
  for hash in hashes{if hash.len()!=64||!hash.bytes().all(|b|b.is_ascii_hexdigit()){return Err(ApiError::new("storage","Invalid retention body hash."));}let all_ids={let mut statement=tx.prepare("SELECT id,size FROM blobs WHERE workspace_id=?1 AND sha256=?2")?;let rows=statement.query_map(params![workspace,hash],|r|Ok((r.get::<_,String>(0)?,r.get::<_,i64>(1)?)))?;rows.collect::<Result<Vec<_>,_>>()?};if all_ids.iter().any(|(id,_)|!candidates.iter().any(|(removed,_,_)|removed==id)){continue;}
   let file=self.root.join("bodies").join(workspace).join(&hash);if file.exists(){let canonical=file.canonicalize()?;if !canonical.starts_with(self.root.join("bodies").canonicalize()?){return Err(ApiError::new("permission","Retention path escaped the content store."));}result.files+=1;result.bytes+=std::fs::metadata(&file)?.len();if apply{tx.execute("INSERT OR IGNORE INTO content_gc(workspace_id,sha256,created_at) VALUES(?1,?2,?3)",params![workspace,hash,now()])?;}}
  }
  if apply{for (id,_,_) in &candidates{tx.execute("DELETE FROM blobs WHERE workspace_id=?1 AND id=?2",params![workspace,id])?;}tx.commit()?;drop(connection);self.recover_content_gc()?;}Ok(result)
 }
 pub fn recover_content_gc(&self)->ApiResult<()>{let _content=crate::platform::content_lock::ContentLock::enter(&self.root)?;let connection=self.lock()?;let jobs={let mut statement=connection.prepare("SELECT workspace_id,sha256 FROM content_gc")?;let rows=statement.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?)))?;rows.collect::<Result<Vec<_>,_>>()?};for (workspace,hash) in jobs{valid_id(&workspace)?;if hash.len()!=64||!hash.bytes().all(|b|b.is_ascii_hexdigit()){return Err(ApiError::new("storage","Invalid pending cleanup hash."));}let referenced:bool=connection.query_row("SELECT EXISTS(SELECT 1 FROM blobs WHERE workspace_id=?1 AND sha256=?2)",params![workspace,hash],|r|r.get(0))?;let file=self.root.join("bodies").join(&workspace).join(&hash);if !referenced&&file.exists(){if !file.canonicalize()?.starts_with(self.root.join("bodies").canonicalize()?){return Err(ApiError::new("permission","Cleanup path escaped the content store."));}std::fs::remove_file(&file)?;}connection.execute("DELETE FROM content_gc WHERE workspace_id=?1 AND sha256=?2",params![workspace,hash])?;}Ok(())}
}
fn collect(value:&Value,ids:&mut HashSet<String>){match value{Value::String(text)=>{if uuid::Uuid::parse_str(text).is_ok(){ids.insert(text.clone());}},Value::Array(rows)=>for row in rows{collect(row,ids)},Value::Object(map)=>for value in map.values(){collect(value,ids)},_=>{}}}
#[cfg(test)]mod tests{use super::*;#[test]fn gc_preserves_shared_content_and_recovers_committed_intent(){let temp=tempfile::tempdir().unwrap();let db=Database::open(temp.path()).unwrap();let workspace=db.create_workspace("Retention").unwrap();let a=db.body_begin(&workspace.id,3,"text/plain").unwrap();db.body_append(&workspace.id,&a,0,"YWJj").unwrap();let first=db.body_finish(&workspace.id,&a).unwrap();let b=db.body_begin(&workspace.id,3,"text/plain").unwrap();db.body_append(&workspace.id,&b,0,"YWJj").unwrap();db.body_finish(&workspace.id,&b).unwrap();db.save(SaveEntity{workspace_id:workspace.id.clone(),id:uuid::Uuid::new_v4().to_string(),kind:"request".into(),name:"Keeps body".into(),expected_revision:0,payload:serde_json::json!({"bodyRef":a})}).unwrap();db.lock().unwrap().execute("UPDATE blobs SET created_at=0",[]).unwrap();let result=db.retain(&workspace.id,1,true).unwrap();assert_eq!(result.body_references,1);assert_eq!(result.files,0);assert_eq!(db.original_body(&workspace.id,&a,10).unwrap(),b"abc");let orphan=self_hash(b"orphan");let dir=db.root.join("bodies").join(&workspace.id);std::fs::write(dir.join(&orphan),b"orphan").unwrap();db.lock().unwrap().execute("INSERT INTO content_gc(workspace_id,sha256,created_at) VALUES(?1,?2,0)",params![workspace.id,orphan]).unwrap();db.recover_content_gc().unwrap();assert!(!dir.join(orphan).exists());assert!(dir.join(first.sha256).exists());}fn self_hash(bytes:&[u8])->String{format!("{:x}",Sha256::digest(bytes))}}
