use super::*;
#[tokio::test]
async fn websocket_binary_roundtrip_and_cancel(){
 let temp=tempfile::tempdir().unwrap();let db=Database::open(temp.path()).unwrap();let workspace=db.create_workspace("WS fixture").unwrap();let listener=tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();let address=listener.local_addr().unwrap();
 let origin=tokio::spawn(async move{let (socket,_)=listener.accept().await.unwrap();let mut stream=tokio_tungstenite::accept_async(socket).await.unwrap();let message=stream.next().await.unwrap().unwrap();assert_eq!(message,Message::Binary(vec![0,255,97].into()));stream.send(message).await.unwrap();let _=stream.next().await;});
 let runtime=ProtocolRuntime::default();let id=uuid::Uuid::new_v4().to_string();runtime.start(&db,StreamInput{workspace_id:workspace.id.clone(),id:id.clone(),url:format!("ws://{address}/echo"),protocol:"WebSocket".into(),headers:vec![],subprotocol:String::new(),last_event_id:String::new()},Arc::new(|_,_,_,_|{})).unwrap();
 for _ in 0..100{if db.get(&workspace.id,&id).unwrap().payload["state"]=="connected"{break;}tokio::time::sleep(Duration::from_millis(20)).await;}
 runtime.send(&workspace.id,&id,"binary","AP9h").unwrap();for _ in 0..100{if db.query(&workspace.id,"flow",200,0).unwrap().len()==2{break;}tokio::time::sleep(Duration::from_millis(20)).await;}
 let frames=db.query(&workspace.id,"flow",200,0).unwrap();assert_eq!(frames.len(),2);assert!(frames.iter().all(|frame|frame.payload["data"]=="AP9h"));runtime.stop(&workspace.id,&id).unwrap();for _ in 0..100{if db.get(&workspace.id,&id).unwrap().payload["state"]=="cancelled"{break;}tokio::time::sleep(Duration::from_millis(20)).await;}assert_eq!(db.get(&workspace.id,&id).unwrap().payload["state"],"cancelled");origin.await.unwrap();
}
#[tokio::test]
async fn sse_dispatches_before_origin_closes(){
 use tokio::io::{AsyncReadExt,AsyncWriteExt};let temp=tempfile::tempdir().unwrap();let db=Database::open(temp.path()).unwrap();let workspace=db.create_workspace("SSE fixture").unwrap();let listener=tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();let address=listener.local_addr().unwrap();let (close_tx,close_rx)=oneshot::channel();
 let origin=tokio::spawn(async move{let (mut socket,_)=listener.accept().await.unwrap();let mut request=[0;8192];socket.read(&mut request).await.unwrap();socket.write_all(b"HTTP/1.1 200 OK\r\nContent-Type: text/event-stream\r\nTransfer-Encoding: chunked\r\n\r\n").await.unwrap();let event=b"id: 7\ndata: streamed\n\n";socket.write_all(format!("{:x}\r\n",event.len()).as_bytes()).await.unwrap();socket.write_all(event).await.unwrap();socket.write_all(b"\r\n").await.unwrap();let _=close_rx.await;});
 let runtime=ProtocolRuntime::default();let id=uuid::Uuid::new_v4().to_string();runtime.start(&db,StreamInput{workspace_id:workspace.id.clone(),id:id.clone(),url:format!("http://{address}/events"),protocol:"SSE".into(),headers:vec![],subprotocol:String::new(),last_event_id:String::new()},Arc::new(|_,_,_,_|{})).unwrap();for _ in 0..100{if !db.query(&workspace.id,"flow",200,0).unwrap().is_empty(){break;}tokio::time::sleep(Duration::from_millis(20)).await;}let records=db.query(&workspace.id,"flow",200,0).unwrap();assert_eq!(records[0].payload["event"]["data"],"streamed");assert_eq!(db.get(&workspace.id,&id).unwrap().payload["state"],"connected");runtime.stop(&workspace.id,&id).unwrap();let _=close_tx.send(());origin.await.unwrap();for _ in 0..100{if db.get(&workspace.id,&id).unwrap().payload["state"]=="cancelled"{break;}tokio::time::sleep(Duration::from_millis(20)).await;}
}
