import {useEffect,useState} from 'react';
import {bridge,bridgeError} from '../../bridge';
import type {StoredEntity,JsonValue} from '../../domain/workspace';
import {useNativeWorkspace} from '../storage/useNativeWorkspace';
import { SelectField } from '../../shell/SelectField';
import { Button } from '../../shell/Button';
import './rules.css';
export function NativeRulesView(){
 const {workspaces,workspaceId,setWorkspaceId,error}=useNativeWorkspace();const [rows,setRows]=useState<StoredEntity[]>([]);const [selected,setSelected]=useState<StoredEntity|null>(null);const [name,setName]=useState('Native rules');const [text,setText]=useState('[]');const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [active,setActive]=useState<{id:string;revision:number}|null>(null);
 useEffect(()=>{let alive=true;setSelected(null);setText('[]');setDirty(false);setActive(null);if(workspaceId)void Promise.all([bridge.command('entity_query',{workspaceId,kind:'rule_set',offset:0,limit:200}),bridge.command('active_rules',{workspaceId})]).then(([rows,active])=>{if(alive){setRows(rows);setActive(active);}}).catch(e=>{if(alive)setMessage(bridgeError(e).message);});return()=>{alive=false;};},[workspaceId]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(bridgeError(e).message);}finally{setBusy(false);}}
 return <div className="workspace-page"><h2>Native traffic rules</h2><p>Ordered URL substring rules execute on the active native capture. Save keeps a draft; Apply waits for engine acknowledgement. Breakpoints expire after 30 seconds and drop the request. User Python/addons are unavailable.</p><p>{active?`Active on next capture: ${rows.find(row=>row.id===active.id)?.name??active.id} · revision ${active.revision}${rows.find(row=>row.id===active.id)?.revision!==active.revision?' (draft changed; re-apply before next start)':''}`:'No persisted active rule set. Apply one while capture is running.'}</p><fieldset disabled={busy}><div className="page-toolbar"><label>Workspace<SelectField label="Workspace" disabled={dirty} value={workspaceId} onChange={setWorkspaceId} options={workspaces.map(w=>({value:w.id,label:w.name}))}/></label><SelectField label="Saved native rules" disabled={dirty} value={selected?.id??''} onChange={value=>{const row=rows.find(r=>r.id===value);setSelected(row??null);setName(row?.name??'Native rules');setText(JSON.stringify(row?.payload.rules??[],null,2));}} options={[{value:'',label:'New rule set'},...rows.map(r=>({value:r.id,label:`${r.name} · r${r.revision}`}))]}/><input aria-label="Rule set name" value={name} onChange={e=>{setName(e.target.value);setDirty(true);}}/></div><label>Ordered rules JSON<textarea rows={20} aria-label="Native rules JSON" value={text} onChange={e=>{setText(e.target.value);setDirty(true);}} style={{width:'100%',fontFamily:'monospace'}}/></label>
<div className="page-toolbar">{['mock','request-header','response-header','request-body','response-body','redirect','map-remote','gateway','mirror','delay','drop','breakpoint','response-breakpoint'].map(action=><Button size="sm" key={action} onClick={()=>{try{const current=JSON.parse(text);if(!Array.isArray(current))throw Error('Rules must be an array');setText(JSON.stringify([...current,{id:crypto.randomUUID(),enabled:true,match:'/example',action,method:'*',key:'X-Debug',value:'enabled',body:'Example response',status:200,target:'https://example.com/',delayMs:100,contentType:'text/plain'}],null,2));setDirty(true);}catch(e){setMessage(bridgeError(e).message);}}}>Add {action}</Button>)}</div><Button disabled={!workspaceId||!name.trim()} onClick={()=>void run(async()=>{const rules=JSON.parse(text) as JsonValue;if(!Array.isArray(rules))throw Error('Rules must be an array');const row=await bridge.command('entity_save',{input:{workspaceId,id:selected?.id??crypto.randomUUID(),kind:'rule_set',name,expectedRevision:selected?.revision??0,payload:{documentType:'capture_rules',rules}}});setSelected(row);setRows(current=>[row,...current.filter(r=>r.id!==row.id)]);setDirty(false);setMessage('Saved draft; click Apply to change active capture.');})}>Save draft</Button><Button variant="default" disabled={!selected||dirty} onClick={()=>void run(async()=>{await bridge.command('rules_apply',{workspaceId,id:selected!.id,expectedRevision:selected!.revision});setActive({id:selected!.id,revision:selected!.revision});setMessage('Engine acknowledged this rule revision. Inspect flow traces to see matching rules.');})}>Apply to active capture</Button><Button disabled={!dirty} onClick={()=>{setText(JSON.stringify(selected?.payload.rules??[],null,2));setDirty(false);}}>Discard edits</Button></fieldset><p role="status">{error||message}</p></div>;
}
