import type { BodyChunk, BodyReference, MigrationInput, MigrationResult, RevisionEvent, RuntimeInfo, SaveEntityInput, StoredEntity, WorkspaceRecord, EntityKind } from '../domain/workspace';
import type { HttpInput, HttpResult } from '../domain/http';
import type { CertificateInfo } from '../domain/certificates';
import type { ScriptInput, ScriptResult } from '../domain/scripts';
import type { OAuthInput,OAuthToken } from '../domain/oauth';
import type { ProxyRecovery } from '../domain/platform';
import type { DiagnosticEntry } from '../features/diagnostics/diagnosticLog';
export type CommandMap = {
  packet_status:{args:undefined;result:PacketStatus};
  packet_interfaces:{args:undefined;result:Array<{index:number;label:string}>};
  packet_start:{args:{interface:number;acknowledged:boolean};result:PacketStatus};
  packet_stop:{args:undefined;result:PacketStatus};
  packet_clear:{args:{acknowledged:boolean};result:PacketStatus};
  packet_keylog_select:{args:undefined;result:PacketStatus};
  packet_keylog_clear:{args:undefined;result:PacketStatus};
  packet_inspect:{args:{name:string};result:PacketRow[]};
  packet_export:{args:{name:string};result:boolean};
  decode_run:{args:{input:{source:string;data:string;key:string}};result:{text:string;sha256:string;bytes:number}};
  sha_file:{args:undefined;result:{name:string;bytes:number;sha224:string;sha256:string;sha384:string;sha512:string}|null};
  lan_status:{args:undefined;result:LanStatus};
  lan_start:{args:{workspaceId:string;host:string;port:number;acknowledged:boolean};result:LanStatus};
  lan_stop:{args:undefined;result:void};
  lan_devices:{args:undefined;result:LanDevice[]};
  lan_pairing:{args:undefined;result:string};
  lan_revoke:{args:{deviceId:string};result:LanDevice[]};
  runtime_diagnostics:{args:undefined;result:{hostWorkingSetBytes:number|null;uptimeSeconds:number}};
  native_error_log:{args:undefined;result:DiagnosticEntry[]};
  native_error_clear:{args:undefined;result:void};
  workbench_detach:{args:undefined;result:void};
  workbench_close:{args:undefined;result:void};
  storage_retention:{args:{workspaceId:string;days:number;apply:boolean;acknowledged:boolean};result:{bodyReferences:number;files:number;bytes:number}};
  workspace_backup:{args:{workspaceId:string;acknowledged:boolean};result:boolean};
  workspace_restore:{args:{name:string;restoreSecrets:boolean;acknowledged:boolean};result:string|null};
  mcp_status:{args:undefined;result:{running:boolean;workspaceId:string|null;port:number|null;token:string|null;draftWrites:boolean;flowReads:boolean}};
  mcp_audit:{args:{workspaceId:string;limit:number};result:Array<{id:number;createdAt:number;operation:string;outcome:string}>};
  mcp_start:{args:{workspaceId:string;port:number;acknowledged:boolean;draftWrites:boolean;flowReads:boolean};result:{running:boolean;workspaceId:string|null;port:number|null;token:string|null;draftWrites:boolean;flowReads:boolean}};
  mcp_stop:{args:undefined;result:void};
  terminal_start:{args:{command:string;acknowledged:boolean};result:void};
  terminal_status:{args:undefined;result:{running:boolean;output:string;truncated:boolean;exitCode:number|null}};
  terminal_stop:{args:undefined;result:void};
  report_preview:{args:{workspaceId:string;sessionId:string};result:import('../domain/workspace').JsonValue};
  report_send:{args:{input:{workspaceId:string;sessionId:string;url:string;acknowledged:boolean;previewDigest:string}};result:number};
  session_import_har:{args:{workspaceId:string};result:string|null};
  session_import_charles_xml:{args:{workspaceId:string};result:string|null};
  session_export_har:{args:{workspaceId:string;sessionId:string;includeBodies:boolean;includeSensitiveHeaders:boolean;acknowledged:boolean};result:boolean};
  body_decode:{args:{workspaceId:string;id:string;encoding:string;protobuf:boolean};result:{base64:string;decodedSize:number;truncated:boolean;protobuf:import('../domain/workspace').JsonValue|null}};
  stream_start:{args:{input:{workspaceId:string;id:string;url:string;protocol:'WebSocket'|'SSE';headers:{key:string;value:string}[];subprotocol:string;lastEventId:string}};result:void};
  stream_stop:{args:{workspaceId:string;id:string};result:void};
  stream_send:{args:{workspaceId:string;id:string;kind:'text'|'binary'|'ping';data:string};result:void};
  analytics_query:{args:{input:{workspaceId:string;sessionId:string|null;since:number;until:number;host:string|null}};result:{requests:number;errors:number;payloadBytes:number;measuredDurations:number;averageMs:number|null;p95Ms:number|null;hosts:Record<string,number>;statuses:Record<string,number>;protocols:Record<string,number>;endpoints:Record<string,number>}};
  flow_search:{args:{workspaceId:string;query:string;sessionId?:string|null;limit:number};result:StoredEntity[]};
  breakpoint_decide:{args:{workspaceId:string;flowId:string;decision:'resume'|'drop';url:string|null;body:string|null;status:number|null};result:void};
  entity_batch:{args:{input:{workspaceId:string;documents:SaveEntityInput[]}};result:StoredEntity[]};
  rules_apply:{args:{workspaceId:string;id:string;expectedRevision:number};result:void};
  active_rules:{args:{workspaceId:string};result:{id:string;revision:number}|null};
  capture_status:{args:undefined;result:import('../domain/capture').CaptureStatus};
  capture_start:{args:{input:{workspaceId:string;name:string;port:number;certificateId:string;upstreamCaPem?:string;mode?:'regular'|'reverse'|'upstream';target?:string|null;sslIntercept?:boolean}};result:import('../domain/capture').CaptureStatus};
  capture_stop:{args:undefined;result:void};
  windows_proxy_recovery:{args:undefined;result:ProxyRecovery};
  windows_proxy_apply:{args:{port:number;acknowledged:boolean};result:ProxyRecovery};
  windows_proxy_restore:{args:{id:string;acknowledged:boolean};result:ProxyRecovery};
  environment_save:{args:{input:{workspaceId:string;id:string;name:string;expectedRevision:number;variables:{key:string;value:string;secret:boolean}[]}};result:StoredEntity};
  environment_load:{args:{workspaceId:string;id:string};result:StoredEntity};
  http_record_scripts:{args:{workspaceId:string;runId:string;summaries:{phase:string;assertions:{name:string;passed:boolean}[];failed:boolean}[]};result:void};
  body_export:{args:{workspaceId:string;id:string};result:number|null};
  oauth_exchange:{args:{input:OAuthInput};result:OAuthToken};
  oauth_cancel:{args:{id:string};result:void};
  entity_import:{args:{input:{workspaceId:string;documents:SaveEntityInput[]}};result:number};
  script_run:{args:{input:ScriptInput};result:ScriptResult};
  script_cancel:{args:{id:string};result:void};
  certificate_list:{args:undefined;result:CertificateInfo[]};
  certificate_create:{args:undefined;result:CertificateInfo};
  certificate_trust:{args:{id:string;fingerprint:string;acknowledged:boolean;install:boolean};result:void};
  http_clear_cookies:{args:{workspaceId:string};result:void};
  windows_proxy_read: { args:undefined; result:{scope:string;enabled:boolean;server:string|null;bypass:string|null;pacUrl:string|null;observedAt:number;message:string} };
  http_send: { args: { input: HttpInput }; result: HttpResult };
  http_cancel: { args: { workspaceId:string; runId:string }; result:void };
  engine_status: { args: undefined; result: { state: string; adapter: string | null; message: string } };
  engine_start: { args: undefined; result: { state: string; adapter: string | null; message: string } };
  engine_stop: { args: undefined; result: void };
  runtime_info: { args: undefined; result: RuntimeInfo };
  workspace_list: { args: undefined; result: WorkspaceRecord[] };
  workspace_create: { args: { name: string }; result: WorkspaceRecord };
  workspace_rename: { args: { id: string; name: string; expectedRevision: number }; result: WorkspaceRecord };
  entity_query: { args: { workspaceId: string; kind: EntityKind; limit: number; offset: number }; result: StoredEntity[] };
  entity_get: { args: { workspaceId: string; id: string }; result: StoredEntity };
  entity_save: { args: { input: SaveEntityInput }; result: StoredEntity };
  entity_delete: { args: { workspaceId: string; id: string; expectedRevision: number }; result: void };
  migration_import: { args: { input: MigrationInput }; result: MigrationResult };
  body_begin: { args: { workspaceId: string; size: number; mimeType: string }; result: string };
  body_append: { args: { workspaceId: string; id: string; offset: number; data: string }; result: number };
  body_finish: { args: { workspaceId: string; id: string }; result: BodyReference };
  body_cancel: { args: { workspaceId: string; id: string }; result: void };
  body_read: { args: { workspaceId: string; id: string; offset: number; length: number }; result: BodyChunk };
  secret_put: { args: { workspaceId: string; id: string; value: string }; result: void };
  secret_get: { args: { workspaceId: string; id: string }; result: string };
  secret_delete: { args: { workspaceId: string; id: string }; result: void };
};
export type PacketStatus={captureAvailable:boolean;analyzerAvailable:boolean;running:boolean;interface:number|null;files:Array<{name:string;bytes:number}>;totalBytes:number;keylogLoaded:boolean;keylogEntries:number;message:string};
export type PacketRow={number:string;time:string;source:string;destination:string;protocol:string;length:string;httpMethod:string;httpStatus:string};
export type LanStatus={running:boolean;workspaceId:string|null;host:string|null;port:number|null;fingerprint:string|null;token:string|null;pairing:string|null;deviceCount:number;ingestedFlows:number;ingestedEvents:number};
export type LanDevice={id:string;label:string;peerIp:string;firstSeen:number;lastSeen:number;flowsIngested:number;eventsIngested:number};
export type Bridge = {
  command<K extends keyof CommandMap>(name: K, args: CommandMap[K]['args']): Promise<CommandMap[K]['result']>;
  onRevision(callback: (event: RevisionEvent) => void): Promise<() => void>;
};
export class BridgeError extends Error {
  constructor(public code: string, message: string, public retryable = false) { super(message); this.name = 'BridgeError'; }
}
export function bridgeError(error: unknown): BridgeError {
  if (error instanceof BridgeError) return error;
  if (error && typeof error === 'object' && 'message' in error) { const value = error as { code?: string; message: string; retryable?: boolean }; return new BridgeError(value.code ?? 'runtime', value.message, value.retryable); }
  return new BridgeError('runtime', typeof error === 'string' ? error : 'Backend operation failed. Your editor remains open.');
}
