export const vietnamese: Readonly<Record<string,string>> = {
  "File": "Tệp",
  "Tools": "Công cụ",
  "View": "Hiển thị",
  "Traffic": "Lưu lượng",
  "Proxy": "Proxy",
  "Certificate": "Chứng chỉ",
  "Help": "Trợ giúp",
  "Settings": "Cài đặt",
  "General": "Chung",
  "Appearance": "Giao diện",
  "API defaults": "Mặc định API",
  "Notifications": "Thông báo",
  "Storage": "Lưu trữ",
  "Shortcuts": "Phím tắt",
  "Integrations": "Tích hợp",
  "History": "Lịch sử",
  "Devices": "Thiết bị",
  "Toolbox": "Hộp công cụ",
  "Environments": "Môi trường",
  "Collections": "Bộ sưu tập",
  "Explorer": "Cây dữ liệu",
  "Tracker": "Theo dõi",
  "Analytics": "Phân tích",
  "Cancel": "Hủy",
  "Close": "Đóng",
  "Save": "Lưu",
  "Delete": "Xóa",
  "Rename": "Đổi tên",
  "Duplicate": "Nhân bản",
  "New document": "Tài liệu mới",
  "Save locally": "Lưu cục bộ",
  "Save to profile": "Lưu vào profile",
  "Apply locally": "Áp dụng cục bộ",
  "Discard edits": "Bỏ thay đổi",
  "Refresh": "Làm mới",
  "Reset": "Đặt lại",
  "Copy": "Sao chép",
  "Download": "Tải xuống",
  "Import": "Nhập",
  "Export": "Xuất",
  "Undo": "Hoàn tác",
  "Redo": "Làm lại",
  "Search": "Tìm kiếm",
  "Name": "Tên",
  "Value": "Giá trị",
  "KEY": "KHÓA",
  "VALUE": "GIÁ TRỊ",
  "ACTIONS": "THAO TÁC",
  "Enable": "Bật",
  "Enabled": "Đã bật",
  "Disabled": "Đã tắt",
  "Secret": "Bí mật",
  "Global": "Toàn cục",
  "Workspace": "Không gian làm việc",
  "Request": "Yêu cầu",
  "Response": "Phản hồi",
  "Summary": "Tóm tắt",
  "Raw": "Dữ liệu thô",
  "Headers": "Headers",
  "Body": "Nội dung",
  "Timing": "Thời gian",
  "Timeline": "Dòng thời gian",
  "Cookies": "Cookies",
  "Authorization": "Xác thực",
  "Query": "Tham số",
  "Script": "Script",
  "Docs": "Tài liệu",
  "None": "Không có",
  "Text": "Văn bản",
  "JSON": "JSON",
  "XML": "XML",
  "Automatic": "Tự động",
  "Send mock": "Gửi giả lập",
  "Sending mock…": "Đang gửi giả lập…",
  "Start capture": "Bắt đầu ghi",
  "Stop capture": "Dừng ghi",
  "Clear traffic": "Xóa lưu lượng",
  "New API request": "Yêu cầu API mới",
  "New HTTP draft": "Bản nháp HTTP mới",
  "New collection": "Bộ sưu tập mới",
  "New scratch request": "Yêu cầu nháp mới",
  "New environment": "Môi trường mới",
  "Add variable": "Thêm biến",
  "No response yet": "Chưa có phản hồi",
  "No body": "Không có nội dung",
  "Import cURL": "Nhập cURL",
  "Format JSON": "Định dạng JSON",
  "None recorded": "Chưa ghi nhận",
  "Import / Export": "Nhập / Xuất",
  "Import / Export JSON": "Nhập / Xuất JSON",
  "Validate import": "Kiểm tra bản nhập",
  "Prepare export": "Chuẩn bị bản xuất",
  "Apply validated import": "Áp dụng bản nhập đã kiểm tra",
  "Copy JSON": "Sao chép JSON",
  "Validate HAR": "Kiểm tra HAR",
  "Prepare HAR export": "Chuẩn bị xuất HAR",
  "Download JSON": "Tải JSON",
  "Open imported preview": "Mở bản xem trước đã nhập",
  "Session name": "Tên phiên",
  "Sessions & HAR": "Phiên và HAR",
  "Performance fixture": "Dữ liệu đo hiệu năng",
  "Import / export HAR": "Nhập / xuất HAR",
  "Save current preview": "Lưu bản xem trước hiện tại",
  "Load 10,000 sample rows": "Tải 10.000 dòng mẫu",
  "Close settings": "Đóng cài đặt",
  "Manage workspaces": "Quản lý workspace",
  "Load preference defaults": "Nạp cài đặt mặc định",
  "Follow redirects": "Theo chuyển hướng",
  "Follow redirects by default": "Theo chuyển hướng theo mặc định",
  "Animations (applies immediately)": "Chuyển động (áp dụng ngay)",
  "Show capture toolbar": "Hiện thanh ghi lưu lượng",
  "Show status bar": "Hiện thanh trạng thái",
  "Default timeout (ms)": "Timeout mặc định (ms)",
  "Timeout (ms)": "Timeout (ms)",
  "Interface zoom": "Thu phóng giao diện",
  "Accent": "Màu nhấn",
  "Theme": "Chủ đề",
  "Traffic row density": "Mật độ dòng lưu lượng",
  "Compact": "Gọn",
  "Comfortable": "Thoáng",
  "Listen host": "Địa chỉ lắng nghe",
  "Port": "Cổng",
  "Protocol": "Giao thức",
  "Upstream URL (no credentials)": "URL upstream (không chứa thông tin đăng nhập)",
  "Bypass patterns": "Mẫu bỏ qua",
  "Apply to Windows": "Áp dụng lên Windows",
  "Actual trust status: UNKNOWN · Fingerprint: unavailable": "Trạng thái tin cậy: CHƯA BIẾT · Chưa có fingerprint",
  "Install CA": "Cài CA",
  "Remove CA": "Gỡ CA",
  "Platform": "Nền tảng",
  "Preview state": "Trạng thái xem trước",
  "Export browser backup": "Xuất backup trình duyệt",
  "Refresh inventory": "Làm mới danh sách",
  "Validate backup": "Kiểm tra backup",
  "Recover into new workspace": "Phục hồi vào workspace mới",
  "Recover documents from browser backup": "Phục hồi tài liệu từ backup trình duyệt",
  "Repository and native bridge": "Repository và bridge native",
  "Repository workspace": "Workspace repository",
  "Record type": "Loại bản ghi",
  "Document name": "Tên tài liệu",
  "Create repository workspace": "Tạo workspace repository",
  "Refresh repository": "Làm mới repository",
  "Select workspace": "Chọn workspace",
  "Save repository document": "Lưu tài liệu repository",
  "Reload document": "Nạp lại tài liệu",
  "Browser → native migration archive": "Lưu trữ migration trình duyệt → native",
  "Preview browser migration": "Xem trước migration trình duyệt",
  "Import archive into native workspace": "Nhập archive vào workspace native",
  "Cancel migration": "Hủy migration",
  "Workspaces": "Workspace",
  "Workspace name": "Tên workspace",
  "Save name": "Lưu tên",
  "Switch": "Chuyển",
  "Current": "Hiện tại",
  "Create workspace": "Tạo workspace",
  "Done": "Xong",
  "Reset shortcuts": "Đặt lại phím tắt",
  "Focus": "Tập trung",
  "Save profile": "Lưu profile",
  "Close workspaces": "Đóng quản lý workspace",
  "New workspace name": "Tên workspace mới",
  "Mixed workspace": "Không gian hỗn hợp",
  "Native panes in one window": "Nhiều pane native trong một cửa sổ",
  "Request URL": "URL yêu cầu",
  "Request name": "Tên yêu cầu",
  "HTTP method": "Phương thức HTTP",
  "Custom HTTP method": "Phương thức HTTP tùy chọn",
  "Response view": "Kiểu hiển thị phản hồi",
  "Request body": "Nội dung yêu cầu",
  "Body type": "Kiểu nội dung",
  "Auth type": "Kiểu xác thực",
  "Request cookies": "Cookies yêu cầu",
  "Request documentation": "Tài liệu yêu cầu",
  "Request timeout": "Timeout yêu cầu",
  "Request HTTP protocol": "Giao thức HTTP yêu cầu",
  "Mock scenario": "Kịch bản giả lập",
  "Success": "Thành công",
  "Network error": "Lỗi mạng",
  "HTTP 500": "HTTP 500",
  "Proxy endpoint": "Địa chỉ proxy",
  "Open HAR file": "Mở tệp HAR",
  "Explore sample traffic": "Xem lưu lượng mẫu",
  "See every request, clearly.": "Xem rõ từng yêu cầu.",
  "READY TO INSPECT": "SẴN SÀNG INSPECT",
  "Search traffic": "Tìm lưu lượng",
  "Search Traffic explorer": "Tìm trong cây lưu lượng",
  "Search API explorer": "Tìm trong cây API",
  "All": "Tất cả",
  "Favorites": "Yêu thích",
  "Favorite": "Yêu thích",
  "Bookmarked": "Đã đánh dấu",
  "Bookmark": "Đánh dấu",
  "Columns": "Cột",
  "Filters": "Bộ lọc",
  "No matching collections.": "Không tìm thấy bộ sưu tập phù hợp.",
  "No collections. Create one or use a scratch request.": "Chưa có bộ sưu tập. Tạo mới hoặc dùng yêu cầu nháp.",
  "No profiles in this collection.": "Chưa có profile trong bộ sưu tập này.",
  "No collections yet. Create one to keep API test profiles.": "Chưa có bộ sưu tập. Tạo mới để lưu profile API.",
  "Move to": "Chuyển tới",
  "Notes": "Ghi chú",
  "Open in API client": "Mở trong API client",
  "PROFILE": "PROFILE",
  "Import environment": "Nhập môi trường",
  "Rename environment": "Đổi tên môi trường",
  "Bulk edit / paste": "Sửa nhiều dòng / dán",
  "Replace rows": "Thay thế các dòng",
  "Append rows": "Thêm vào cuối",
  "Cancel bulk edit": "Hủy sửa nhiều dòng",
  "Binary file": "Tệp nhị phân",
  "Form URL encoded": "Form URL encoded",
  "Multipart draft": "Bản nháp multipart",
  "Clear file": "Bỏ chọn tệp",
  "Request binary file": "Tệp nhị phân yêu cầu",
  "Clear": "Xóa nội dung",
  "Encode": "Mã hóa",
  "Decode": "Giải mã",
  "Generate": "Tạo",
  "Input": "Đầu vào",
  "Output": "Đầu ra",
  "Regex": "Biểu thức chính quy",
  "Pattern": "Mẫu",
  "Flags": "Cờ",
  "Run": "Chạy",
  "Stop": "Dừng",
  "Connect": "Kết nối",
  "Disconnect": "Ngắt kết nối",
  "Save current layout": "Lưu layout hiện tại",
  "Reset geometry": "Đặt lại bố cục",
  "Workspace layouts": "Layout workspace",
  "Apply": "Áp dụng",
  "Layout name": "Tên layout",
  "No named layouts yet.": "Chưa có layout đặt tên.",
  "Collapse": "Thu gọn",
  "Expand": "Mở rộng",
  "Maximize": "Phóng lớn",
  "Customize tabs": "Tùy chỉnh tab",
  "Reset tabs": "Đặt lại tab",
  "Detach window": "Tách cửa sổ",
  "Inspector tabs": "Tab inspector",
  "Original body": "Nội dung gốc",
  "No supported image bytes in this preview.": "Bản xem trước chưa có byte ảnh được hỗ trợ.",
  "Not valid JSON; showing the original text.": "JSON không hợp lệ; đang hiển thị văn bản gốc.",
  "Text is a UTF-8 preview; Hex and original-body download preserve HAR bytes.": "Văn bản là bản xem UTF-8; Hex và tải nội dung gốc giữ nguyên byte HAR.",
  "Table": "Bảng",
  "Board": "Board",
  "Split": "Chia pane",
  "Status": "Trạng thái",
  "Category": "Danh mục",
  "Priority": "Ưu tiên",
  "Tags": "Tags",
  "Comment": "Ghi chú",
  "Bulk status": "Đổi trạng thái hàng loạt",
  "Saved views": "View đã lưu",
  "Add issue": "Thêm mục theo dõi",
  "New item": "Mục mới",
  "Search tools": "Tìm công cụ",
  "Copy output": "Sao chép kết quả",
  "Clear input": "Xóa đầu vào",
  "Request variables": "Biến yêu cầu",
  "Collection variables": "Biến collection",
  "Profile variables": "Biến profile",
  "Variable name": "Tên biến",
  "Value or {{variable}}": "Giá trị hoặc {{variable}}",
  "Initial value": "Giá trị ban đầu",
  "Current value": "Giá trị hiện tại",
  "Check updates": "Kiểm tra cập nhật",
  "Send feedback": "Gửi phản hồi",
  "Send test notification": "Gửi thông báo thử",
  "Troubleshooting": "Khắc phục sự cố",
  "Changelog": "Lịch sử thay đổi",
  "Show in-app toasts": "Hiện thông báo trong app",
  "Toast duration": "Thời lượng thông báo",
  "Mark all read": "Đánh dấu tất cả đã đọc",
  "Clear history": "Xóa lịch sử",
  "No notifications yet.": "Chưa có thông báo."
};
