import { useEffect, useState } from 'react';
import type { Tab } from '../../domain/types';
import { ApiView } from './ApiView';
import { SetupFileView } from '../../shell/ExplorerSidebar';
import './multiPane.css';
export function ApiWorkspace({ tabs, active, count, direction, environment, flash, onDirty, onCount, ratio, onRatio }: { tabs: Tab[]; active: Tab; count: number; direction: 'horizontal' | 'vertical'; environment: string; flash: (m:string)=>void; onDirty:(id:number,dirty:boolean)=>void; onCount:(count:number)=>void;ratio:number;onRatio:(ratio:number)=>void }) {
  const [slots,setSlots]=useState<Record<number,number>>(()=>{try{return JSON.parse(localStorage.getItem('traffic-studio-pane-slots-v1')??'{}');}catch{return{};}});
  useEffect(()=>{localStorage.setItem('traffic-studio-pane-slots-v1',JSON.stringify(slots));},[slots]);
  const choices=tabs.filter(t=>t.view==='api' && t.id!==active.id);
  const used=new Set([active.id]);const shown=[active,...Array.from({length:count-1},(_,i)=>{const choice=choices.find(t=>t.id===slots[i+1]&&!used.has(t.id))??choices.find(t=>!used.has(t.id));if(choice)used.add(choice.id);return choice;})];
  return <div className={`api-multi-workspace ${direction}`}><div className="api-multi-toolbar"><label>API panes <select aria-label="API pane count" value={count} onChange={e=>onCount(Number(e.target.value))}>{[1,2,3,4].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Column ratio <input aria-label="Multi-pane column ratio" type="range" min={30} max={70} value={ratio} onChange={e=>onRatio(Number(e.target.value))}/></label><span>Drag API tabs onto a pane to choose its document.</span></div><div className={`api-multi-grid panes-${count}`} style={direction==='horizontal'||count===4?{gridTemplateColumns:`minmax(280px,${ratio}%) minmax(280px,1fr)`}:undefined}>{shown.map((tab,i)=><div className="api-multi-pane" key={i} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();const id=Number(e.dataTransfer.getData('text/plain'));if(i>0 && choices.some(t=>t.id===id))setSlots(v=>({...v,[i]:id}));}}><div className="api-pane-caption"><span>Pane {i+1}</span>{i>0 && <select aria-label={`Document in pane ${i+1}`} value={tab?.id ?? ''} onChange={e=>setSlots(v=>({...v,[i]:Number(e.target.value)}))}><option value="" disabled>Select a document</option>{choices.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select>}</div>{tab ? tab.node?.kind==='setup' ? <SetupFileView node={tab.node}/> : <ApiView key={tab.id} flash={flash} environment={environment} requestName={tab.node?.name ?? tab.label} profileId={tab.node?.kind==='profile'?tab.node.id:undefined} tabId={tab.id} onDirty={dirty=>onDirty(tab.id,dirty)}/> : <div className="no-results">Open another API tab to use this pane.</div>}</div>)}</div></div>;
}
