import { useState,useRef,useEffect } from 'react';
import { bridge,bridgeError } from '../../bridge';
import { readCollections,type ApiCollection } from './collections';
import { collectionDocuments } from './nativeDocuments';
import { sanitizeVariables } from '../environments/resolution';
import { Button } from '../../shell/Button';
const credential=(key:string)=>/^(authorization|proxy-authorization|cookie|set-cookie|x-api-key|api-key)$/i.test(key.trim());
export function BrowserCollectionMigration({workspaceId}:{workspaceId:string}){
  const [preview,setPreview]=useState<ApiCollection[]|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const generation=useRef(0);useEffect(()=>{generation.current++;setPreview(null);setMessage('');setBusy(false);return()=>{generation.current++;};},[workspaceId]);
  function prepare(){try{const source=readCollections();if(source.length>500||source.reduce((sum,c)=>sum+c.profiles.length,0)>2000)throw Error('Migration exceeds 500 folders/2000 requests.');const ids=new Map(source.map(c=>[c.id,crypto.randomUUID()]));const next=source.map(c=>{if(c.parentId&&!ids.has(c.parentId))throw Error('Source folder parent is missing.');return{...c,id:ids.get(c.id)!,parentId:c.parentId?ids.get(c.parentId):null,variables:sanitizeVariables(c.variables),profiles:c.profiles.map(p=>({...p,id:crypto.randomUUID(),variables:sanitizeVariables(p.variables),headers:p.headers.filter(h=>!credential(h.key))}))};});setPreview(next);setMessage('Review before import. New IDs will be used; browser source stays unchanged. URLs/bodies can contain private data.');}catch(e){setPreview(null);setMessage(bridgeError(e).message);}}
  async function migrate(){if(!preview||!workspaceId)return;const operation=generation.current;setBusy(true);setMessage('');try{const count=await bridge.command('entity_import',{input:{workspaceId,documents:collectionDocuments(preview,workspaceId)}});if(generation.current===operation){setPreview(null);setMessage(`Imported ${count} folder/request documents atomically. Load native requests to open them. Browser source preserved.`);}}catch(e){if(generation.current===operation)setMessage(bridgeError(e).message);}finally{if(generation.current===operation)setBusy(false);}}
  return <section aria-label="Browser collection migration"><Button size="sm" disabled={busy||!workspaceId} onClick={prepare}>Preview browser → native collections migration</Button>{preview&&<><p>{preview.length} folders · {preview.reduce((sum,c)=>sum+c.profiles.length,0)} requests. Inherited variables and transport drafts are retained; file selections and credentials are excluded.</p><details><summary>Review folders</summary><ul>{preview.map(c=><li key={c.id}>{c.name} · {c.profiles.length} requests</li>)}</ul></details><Button size="sm" disabled={busy||!workspaceId||!preview.length} onClick={()=>void migrate()}>Import snapshot to selected native workspace</Button><Button size="sm" disabled={busy} onClick={()=>setPreview(null)}>Discard migration preview</Button></>}<p role="status">{message}</p></section>;
}
