import { useEffect, useState } from 'react';
import { Code2, Folder, Plus, Search } from 'lucide-react';
import { readCollections, writeCollections } from './collections';
import type { ExplorerNode } from '../../shell/ExplorerSidebar';

export function CollectionExplorer({ onOpen, onManage, onNew }: { onOpen: (node: ExplorerNode) => void; onManage: () => void; onNew: () => void }) {
  const [legacy,setLegacy]=useState<ExplorerNode[]>(()=>{try{return JSON.parse(localStorage.getItem('traffic-studio-explorer-v1')??'[]').filter((n:ExplorerNode)=>n.kind==='setup');}catch{return[];}});
  const [items, setItems] = useState(readCollections);
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState<string[]>([]);
  useEffect(() => { const refresh = () => setItems(readCollections()); window.addEventListener('traffic-studio-collections-change', refresh); return () => window.removeEventListener('traffic-studio-collections-change', refresh); }, []);
  const depth=(id:string)=>{let d=0,c=items.find(c=>c.id===id);const seen=new Set<string>();while(c?.parentId&&!seen.has(c.parentId)){seen.add(c.parentId);d++;c=items.find(x=>x.id===c!.parentId);}return d;};
  const shown = items.filter(c => `${c.name} ${c.profiles.map(p => p.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <aside className="explorer-sidebar" aria-label="API explorer"><div className="explorer-title"><span>EXPLORER · LOCAL</span><Code2 size={15}/></div><div className="api-sidebar-tabs"><button className="active">Explorer</button><button onClick={onManage}>Collections</button></div><div className="explorer-search"><Search size={13}/><input aria-label="Search API explorer" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search collections and requests"/></div><div className="explorer-tree"><button className="sidebar-action" onClick={onNew}><Plus size={14}/> New scratch request</button><button className="sidebar-action" onClick={() => { const name = `Collection ${items.length + 1}`; writeCollections([...items, { id: crypto.randomUUID(), name, profiles: [] }]); }}><Folder size={14}/> New collection</button>{shown.length ? shown.map(c => <div key={c.id} style={{paddingLeft:depth(c.id)*12}}><button className="sidebar-action" aria-expanded={open.includes(c.id) || !!query} onClick={() => setOpen(v => v.includes(c.id) ? v.filter(id => id !== c.id) : [...v, c.id])}><Folder size={14}/>{c.name} ({c.profiles.length})</button>{(open.includes(c.id) || query) && c.profiles.filter(p => !query || c.name.toLowerCase().includes(query.toLowerCase()) || p.name.toLowerCase().includes(query.toLowerCase())).map(p => <button className="sidebar-action" key={p.id} style={{ paddingLeft: 28 }} onClick={() => onOpen({ id: p.id, parentId: c.id, name: p.name, kind: 'profile' })}><Code2 size={13}/>{p.method} · {p.name}</button>)}</div>) : <p className="explorer-hint">{query ? 'No matching collections.' : 'No collections. Create one or use a scratch request.'}</p>}<details><summary className="sidebar-action">Setup documents</summary>{legacy.map(n=><button key={n.id} className="sidebar-action" onClick={()=>onOpen(n)}>{n.name}</button>)}<button className="sidebar-action" onClick={()=>{const node:ExplorerNode={id:crypto.randomUUID(),parentId:null,kind:'setup',name:`settings-${legacy.length+1}.json`};const all=JSON.parse(localStorage.getItem('traffic-studio-explorer-v1')??'[]');localStorage.setItem('traffic-studio-explorer-v1',JSON.stringify([...all,node]));setLegacy([...legacy,node]);onOpen(node);}}>New setup document</button></details><p className="explorer-hint">Explorer and Collections use the same profiles. Manage rename, move and delete in Collections.</p></div></aside>;
}
