import { UiText } from '../localization';
import { Button } from '../../shell/Button';
import { useRef, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { parsePairs, createPairId, type EditablePair } from './pairs';
export function KeyValueGrid({ rows, onChange, label }: { rows: EditablePair[]; onChange: (rows: EditablePair[]) => void; label: string }) {
  const [bulk, setBulk] = useState<string | null>(null); const [error, setError] = useState('');
  const undo = useRef<EditablePair[][]>([]), redo = useRef<EditablePair[][]>([]);
  const [,redraw] = useState(0);
  const root=useRef<HTMLDivElement>(null);
  function commit(next: EditablePair[]) { if(next.length>1000){setError('Maximum 1,000 rows.');return;} undo.current.push(rows.map(row=>({...row})));undo.current=undo.current.slice(-50);redo.current=[];onChange(next);setError(''); }
  function history(direction:'undo'|'redo') { const from=direction==='undo'?undo:redo;const to=direction==='undo'?redo:undo;const next=from.current.pop();if(next){to.current.push(rows.map(row=>({...row})));onChange(next);redraw(v=>v+1);} }
  function add() { commit([...rows,{id:createPairId(),key:'',value:'',enabled:true}]);requestAnimationFrame(()=>root.current?.querySelectorAll<HTMLInputElement>('input[data-cell="key"]').item(rows.length)?.focus()); }
  function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=rows.length)return;const next=[...rows];[next[index],next[target]]=[next[target],next[index]];commit(next);}
  return <div ref={root} className="key-value-grid" onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&['z','y'].includes(event.key.toLowerCase())){event.preventDefault();event.stopPropagation();history(event.key.toLowerCase()==='y'||event.shiftKey?'redo':'undo');}}}>
    <div className="pair-toolbar" role="toolbar" aria-label={`${label} edit actions`}><Button variant="ghost" size="sm" type="button" disabled={!undo.current.length} onClick={()=>history('undo')}><UiText text={"Undo"}/></Button><Button variant="ghost" size="sm" type="button" disabled={!redo.current.length} onClick={()=>history('redo')}><UiText text={"Redo"}/></Button><Button variant="ghost" size="sm" type="button" onClick={()=>setBulk(rows.map(row=>`${row.key}\t${row.value}`).join('\n'))}><UiText text={"Bulk edit / paste"}/></Button></div>
    {bulk!==null && <div className="pair-bulk-editor"><p>One key/value pair per line, separated by tab, colon or equals. Duplicate keys remain separate rows.</p><textarea aria-label={`Bulk ${label}`} value={bulk} onChange={e=>setBulk(e.target.value)}/><Button size="sm" onClick={()=>{try{commit(parsePairs(bulk));setBulk(null);}catch(e){setError(e instanceof Error?e.message:'Invalid pairs');}}}><UiText text={"Replace rows"}/></Button><Button size="sm" onClick={()=>{try{const parsed=parsePairs(bulk);if(rows.length+parsed.length>1000)throw Error('Maximum 1,000 rows.');commit([...rows,...parsed]);setBulk(null);}catch(e){setError(e instanceof Error?e.message:'Invalid pairs');}}}><UiText text={"Append rows"}/></Button><Button size="sm" onClick={()=>setBulk(null)}><UiText text={"Cancel bulk edit"}/></Button></div>}
    <div className="pair-head"><span/><span><UiText text={"KEY"}/></span><span><UiText text={"VALUE"}/></span><span><UiText text={"ACTIONS"}/></span></div>
    {rows.map((row,index)=><div className="pair-row" key={row.id}><input type="checkbox" checked={row.enabled} aria-label={`Enable ${label} row ${index+1}`} onChange={e=>commit(rows.map(r=>r.id===row.id?{...r,enabled:e.target.checked}:r))}/>{(['key','value'] as const).map(cell=><input key={cell} data-cell={cell} className="rounded-none! focus-visible:outline-none! focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-[#f59e0b]/60" aria-label={`${label} ${cell} ${index+1}`} placeholder={cell} value={row[cell]} onChange={e=>commit(rows.map(r=>r.id===row.id?{...r,[cell]:e.target.value}:r))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}} onPaste={e=>{const text=e.clipboardData.getData('text');if(text.includes('\n')||text.includes('\t')){e.preventDefault();try{const parsed=parsePairs(text);commit([...rows,...parsed]);}catch(error){setError(error instanceof Error?error.message:'Invalid clipboard pairs');}}}}/>)}<div className="pair-row-actions"><Button variant="ghost" size="icon" className="!rounded-none !border-0 !bg-transparent !shadow-none" aria-label={`Move ${label} row ${index+1} up`} disabled={index===0} onClick={()=>move(index,-1)}>↑</Button><Button variant="ghost" size="icon" className="!rounded-none !border-0 !bg-transparent !shadow-none" aria-label={`Move ${label} row ${index+1} down`} disabled={index===rows.length-1} onClick={()=>move(index,1)}>↓</Button><Button variant="ghost" size="icon" className="!rounded-none !border-0 !bg-transparent !shadow-none" aria-label={`Duplicate ${label} row ${index+1}`} onClick={()=>commit([...rows.slice(0,index+1),{...row,id:createPairId()},...rows.slice(index+1)])}>⧉</Button><Button variant="ghost" size="icon" className="!rounded-none !border-0 !bg-transparent !shadow-none" aria-label={`Remove ${label} row ${index+1}`} onClick={()=>commit(rows.filter(r=>r.id!==row.id))}><Trash2 size={13}/></Button></div></div>)}
    <Button className="pair-add" onClick={add}><Plus size={14}/> Add {label}</Button>{error&&<p role="alert" className="tool-error">{error}</p>}
  </div>;
}
