import { useEffect, useRef, useState } from 'react';
import { bridge, bridgeError } from '../../bridge';
import type { JsonValue, StoredEntity } from '../../domain/workspace';
import { parseNativeDraft, type RequestDraft } from './requestDraft';
import { validateVariables } from '../environments/resolution';
export function NativeRequestDocuments({workspaceId,draft,onLoad,onSaved}:{workspaceId:string;draft:RequestDraft;onLoad:(draft:RequestDraft)=>void;onSaved:()=>void}) {
  const [rows,setRows]=useState<StoredEntity[]>([]);const [selected,setSelected]=useState<StoredEntity|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const generation=useRef(0),latest=useRef(draft);latest.current=draft;
  const [offset,setOffset]=useState(0);
  useEffect(()=>{generation.current++;setRows([]);setSelected(null);setMessage('');setBusy(false);return()=>{generation.current++;};},[workspaceId]);
  async function action(run:(operation:number)=>Promise<void>){const operation=generation.current;setBusy(true);setMessage('');try{await run(operation);}catch(error){if(generation.current===operation)setMessage(bridgeError(error).message);}finally{if(generation.current===operation)setBusy(false);}}
  async function refresh(operation:number,nextOffset=0){const result=await bridge.command('entity_query',{workspaceId,kind:'request',limit:100,offset:nextOffset});if(generation.current===operation){setRows(result);setOffset(nextOffset);}}
  async function save(copy:boolean,operation:number){const snapshot=JSON.stringify(draft);const record=await bridge.command('entity_save',{input:{workspaceId,id:copy||!selected?crypto.randomUUID():selected.id,kind:'request',name:draft.name.trim()||'Untitled request',expectedRevision:copy||!selected?0:selected.revision,payload:{...(!copy&&selected?selected.payload:{}),documentType:'http_request',draft:JSON.parse(snapshot) as JsonValue}}});if(generation.current===operation){setSelected(record);setMessage('Native request committed. Credentials excluded; body and URL remain local data.');if(JSON.stringify(latest.current)===snapshot)onSaved();await refresh(operation);}}
  async function load(row:StoredEntity,operation:number){if(!window.confirm('Replace the current request draft with this native document?'))return;const snapshot=JSON.stringify(latest.current);const record=await bridge.command('entity_get',{workspaceId,id:row.id});const parsed=parseNativeDraft(record.payload.draft);const layers=[];const seen=new Set<string>();let parent=record.payload.collectionId;while(typeof parent==='string'){if(seen.has(parent)||seen.size>=24)throw Error('Native collection hierarchy is cyclic or too deep.');seen.add(parent);const folder=await bridge.command('entity_get',{workspaceId,id:parent});if(folder.kind!=='collection')throw Error('Request parent is not a native collection.');layers.unshift(validateVariables(folder.payload.variables));parent=folder.payload.parentId;}parsed.variables=[...layers.flat(),...(parsed.variables??[])];if(generation.current===operation){if(JSON.stringify(latest.current)!==snapshot)throw Error('Editor changed while loading. Your draft was kept; retry.');onLoad(parsed);setSelected(record);setMessage('Loaded request with a snapshot of inherited native folder variables. Secrets must be entered in memory.');}}
  return <section className="native-request-documents"><button disabled={busy||!workspaceId} onClick={()=>void action(operation=>save(false,operation))}>{selected?'Save native request':'Save as native request'}</button><button disabled={busy||!workspaceId} onClick={()=>void action(operation=>save(true,operation))}>Save native copy</button><button disabled={busy||!workspaceId} onClick={()=>void action(refresh)}>Load native requests</button><button disabled={busy||!workspaceId||offset===0} onClick={()=>void action(op=>refresh(op,Math.max(0,offset-100)))}>Previous requests</button><button disabled={busy||!workspaceId||rows.length<100} onClick={()=>void action(op=>refresh(op,offset+100))}>Next requests</button>{rows.map(row=><button key={row.id} disabled={busy} onClick={()=>void action(operation=>load(row,operation))}>{row.name} · r{row.revision}</button>)}<p role="status">{message}</p></section>;
}
