import { useEffect,useRef,useState } from 'react';
import { bridge,bridgeError } from '../../bridge';
import type { OAuthInput,OAuthToken } from '../../domain/oauth';
import { SelectField } from '../../shell/SelectField';
import { Button } from '../../shell/Button';
const initial:Omit<OAuthInput,'id'>={endpoint:'',grant:'client_credentials',clientId:'',clientSecret:'',clientAuth:'body',scope:'',code:'',redirectUri:'',verifier:'',refreshToken:''};
type Pkce={verifier:string;state:string;redirect:string;expiresAt:number;used:boolean};
function base64url(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function endpoint(value:string){const url=new URL(value);if(url.username||url.password||url.hash||!(url.protocol==='https:'||url.protocol==='http:'&&['127.0.0.1','[::1]'].includes(url.hostname)))throw Error('Use HTTPS or literal loopback HTTP without URL credentials/fragment.');return url;}
export function OAuthPanel({native,onToken}:{native:boolean;onToken:(token:string)=>void}){
  const [form,setForm]=useState(initial);const [authorizeEndpoint,setAuthorizeEndpoint]=useState('');const [authorizeUrl,setAuthorizeUrl]=useState('');const [callback,setCallback]=useState('');
  const [token,setToken]=useState<OAuthToken|null>(null);const [expiry,setExpiry]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const pkce=useRef<Pkce|null>(null);const active=useRef<{id:string;cancelled:boolean}|null>(null);const alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;pkce.current=null;const run=active.current;if(run){run.cancelled=true;void bridge.command('oauth_cancel',{id:run.id}).catch(()=>{});}};},[]);
  function update(patch:Partial<typeof form>){setForm({...form,...patch});pkce.current=null;setAuthorizeUrl('');setCallback('');}
  async function prepare(){setBusy(true);setMessage('');try{if(!form.clientId||!form.redirectUri)throw Error('Set client ID and your provider-registered redirect URI.');const url=endpoint(authorizeEndpoint);const redirect=endpoint(form.redirectUri);if(redirect.search)throw Error('This manual PKCE flow requires a redirect URI without query parameters.');const verifier=base64url(crypto.getRandomValues(new Uint8Array(32)));const challenge=base64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));const state=base64url(crypto.getRandomValues(new Uint8Array(32)));url.searchParams.set('response_type','code');url.searchParams.set('client_id',form.clientId);url.searchParams.set('redirect_uri',form.redirectUri);url.searchParams.set('scope',form.scope);url.searchParams.set('state',state);url.searchParams.set('code_challenge',challenge);url.searchParams.set('code_challenge_method','S256');if(alive.current){pkce.current={verifier,state,redirect:redirect.toString(),expiresAt:Date.now()+10*60*1000,used:false};setAuthorizeUrl(url.toString());setCallback('');setMessage('Copy the URL into your browser. After approval, paste the resulting redirect URL. This app does not start a callback listener.');}}catch(e){if(alive.current)setMessage(bridgeError(e).message);}finally{if(alive.current)setBusy(false);}}
  async function exchange(grant=form.grant){if(active.current)return;setBusy(true);setMessage('');const run={id:crypto.randomUUID(),cancelled:false};active.current=run;
    try{let input:OAuthInput={...form,id:run.id,grant};let current:Pkce|null=null;
      if(grant==='authorization_code'){current=pkce.current;if(!current||current.used||Date.now()>current.expiresAt)throw Error('Prepare a fresh PKCE authorization URL first.');const returned=new URL(callback),expected=new URL(current.redirect);if(returned.protocol!==expected.protocol||returned.host!==expected.host||returned.pathname!==expected.pathname||returned.hash||returned.username||returned.password||returned.searchParams.getAll('state').length!==1||returned.searchParams.get('state')!==current.state||returned.searchParams.getAll('code').length!==1||returned.searchParams.has('error'))throw Error('Callback URL, state, or authorization code does not match this PKCE request.');const code=returned.searchParams.get('code');if(!code)throw Error('Callback contains no authorization code.');input={...input,code,redirectUri:current.redirect,verifier:current.verifier};current.used=true;}
      if(grant==='refresh_token'){if(!token?.refreshToken&&!form.refreshToken)throw Error('No refresh token available.');input.refreshToken=token?.refreshToken??form.refreshToken;}
      const next=await bridge.command('oauth_exchange',{input});if(alive.current&&!run.cancelled){setToken({...next,refreshToken:next.refreshToken??(grant==='refresh_token'?input.refreshToken:null)});setExpiry(next.expiresIn!=null&&Number.isSafeInteger(next.expiresIn)&&next.expiresIn<=31536000?Date.now()+next.expiresIn*1000:null);onToken(next.accessToken);setCallback('');pkce.current=null;setAuthorizeUrl('');setMessage('Bearer token applied to this request in memory. Token exchanges are not recorded in HTTP history.');}
    }catch(e){if(alive.current)setMessage(bridgeError(e).message);}finally{if(active.current===run)active.current=null;if(alive.current)setBusy(false);}}
  function clear(){setToken(null);setExpiry(null);pkce.current=null;setAuthorizeUrl('');setCallback('');setForm({...form,clientSecret:'',code:'',verifier:'',refreshToken:''});onToken('');setMessage('Credentials, tokens and PKCE state cleared.');}
  return <section aria-label="OAuth token acquisition"><h4>OAuth 2</h4><p>Explicit token exchange with verified TLS and no redirects. Credentials/tokens stay in memory. PKCE uses a manual browser round trip; callback listening and discovery are pending.</p>
    <label>Grant<SelectField label="Grant" disabled={busy} value={form.grant} onChange={value=>update({grant:value})} options={[{value:'client_credentials',label:'Client credentials'},{value:'authorization_code',label:'Authorization code + PKCE'},{value:'refresh_token',label:'Refresh token'}]}/></label>
    <label>Token endpoint<input disabled={busy} value={form.endpoint} onChange={e=>update({endpoint:e.target.value})}/></label>
    <label>Client ID<input disabled={busy} value={form.clientId} onChange={e=>update({clientId:e.target.value})}/></label>
    <label>Client secret<input disabled={busy} type="password" autoComplete="off" value={form.clientSecret} onChange={e=>update({clientSecret:e.target.value})}/></label>
    <label>Client authentication<SelectField label="Client authentication" disabled={busy} value={form.clientAuth} onChange={value=>update({clientAuth:value})} options={[{value:'body',label:'Form body'},{value:'basic',label:'HTTP Basic'},{value:'none',label:'Public client'}]}/></label>
    <label>Scope<input disabled={busy} value={form.scope} onChange={e=>update({scope:e.target.value})}/></label>
    {form.grant==='authorization_code'&&<><label>Authorization endpoint<input disabled={busy} value={authorizeEndpoint} onChange={e=>{setAuthorizeEndpoint(e.target.value);pkce.current=null;setAuthorizeUrl('');}}/></label><label>Registered redirect URI<input disabled={busy} value={form.redirectUri} onChange={e=>update({redirectUri:e.target.value})}/></label><Button size="sm" disabled={!native||busy} onClick={()=>void prepare()}>Prepare PKCE authorization</Button>{authorizeUrl&&<><textarea readOnly aria-label="PKCE authorization URL" value={authorizeUrl}/><Button size="sm" disabled={busy} onClick={()=>void navigator.clipboard.writeText(authorizeUrl).then(()=>setMessage('Authorization URL copied.')).catch(()=>setMessage('Select and copy the URL manually.'))}>Copy authorization URL</Button><textarea disabled={busy} aria-label="OAuth callback URL" value={callback} onChange={e=>setCallback(e.target.value)}/></>}</>}
    {form.grant==='refresh_token'&&<label>Refresh token<input type="password" autoComplete="off" disabled={busy} value={form.refreshToken} onChange={e=>update({refreshToken:e.target.value})} placeholder={token?.refreshToken?'A refresh token is held in memory':''}/></label>}
    <Button size="sm" disabled={!native||busy} onClick={()=>void exchange()}>Acquire and use token</Button>{busy&&<Button size="sm" onClick={()=>{const run=active.current;if(run){run.cancelled=true;void bridge.command('oauth_cancel',{id:run.id}).catch(e=>setMessage(bridgeError(e).message));}}}>Cancel token exchange</Button>}
    {token&&<><p>Token held in memory · {expiry?`expires ${new Date(expiry).toLocaleString()}`:'expiry unknown'}</p><Button size="sm" disabled={!native||busy||!token.refreshToken} onClick={()=>void exchange('refresh_token')}>Refresh held token</Button></>}
    <Button size="sm" disabled={busy} onClick={clear}>Clear OAuth credentials</Button><p role="status">{!native?'Native Windows app required. ':''}{message}</p>
  </section>;
}
