import { UiText } from '../localization';
import { Button } from '../../shell/Button';
import { SelectField } from '../../shell/SelectField';
import { useState } from 'react';
import { KeyValueGrid, type EditablePair } from './KeyValueGrid';
export const bodyModes = ['None','Text','JSON','XML','Form URL encoded','Multipart draft','Binary file'] as const;
function readForm(body:string):EditablePair[]{try{const value=JSON.parse(body);if(Array.isArray(value)&&value.every(row=>row&&typeof row.key==='string'&&typeof row.value==='string'&&typeof row.enabled==='boolean'))return value.map((row,i)=>({...row,id:row.id??i+1}));}catch{/* Preserve original body when switching modes. */}return[];}
export function RequestBodyEditor({body,mode,onChange,file,onFile,native=false}:{body:string;mode:string;onChange:(patch:{body?:string;bodyMode?:string})=>void;file:File|null;onFile:(file:File|null)=>void;native?:boolean}){
  const [error,setError]=useState('');
  const structured=mode==='Form URL encoded'||mode==='Multipart draft';
  return <div className="api-field-body"><SelectField label="Body type" value={mode} onChange={value=>{onChange({bodyMode:value});setError('');}} options={bodyModes.map(value=>({value,label:value}))}/>
    {structured?<><p>{mode==='Multipart draft'?(native?'Enabled text fields are sent as multipart with a generated boundary. Add file attachments below.':'Multipart fields are local preview drafts.'):(native?'Enabled form fields are URL encoded and sent by the native client.':'Enabled form fields are URL encoded for the mock input.')}</p><KeyValueGrid label="body field" rows={readForm(body)} onChange={rows=>onChange({body:JSON.stringify(rows)})}/>{body&&!readForm(body).length&&<p>Previous raw body is retained. Add a field to replace it with structured form rows.</p>}</>:mode==='Binary file'?<><input type="file" aria-label="Request binary file" onChange={e=>{const next=e.target.files?.[0]??null;if(next&&next.size>1024*1024*1024){setError('File exceeds 1 GiB native body-store limit.');return;}onFile(next);setError('');}}/>{file?<p>{file.name} · {file.size.toLocaleString()} bytes · memory reference only</p>:<p>No file selected. Files are not stored in browser drafts; reselect after reload.</p>}<Button size="sm" disabled={!file} onClick={()=>onFile(null)}><UiText text={"Clear file"}/></Button><p>{native?'Send HTTP streams the selected file through the native body store. Reselect files after reload.':'Mock Send does not upload file bytes.'}</p></>:<><textarea disabled={mode==='None'} spellCheck={false} aria-label="Request body" value={body} onChange={e=>onChange({body:e.target.value})} placeholder="Request body"/>{mode==='JSON'&&<Button size="sm" onClick={()=>{try{onChange({body:JSON.stringify(JSON.parse(body),null,2)});setError('');}catch{setError('Request body is not valid JSON.');}}}><UiText text={"Format JSON"}/></Button>}</>}{error&&<p role="alert" className="tool-error">{error}</p>}
  </div>;
}
