import { useRef, useState } from 'react';
import { X } from 'lucide-react';
import { defaults, usePreferences, type Preferences } from './preferences';
import './settings.css';
import { Personalization } from './Personalization';
import { IntegrationDrafts } from './IntegrationDrafts';
import { useDialogFocus } from '../../shell/useDialogFocus';

export const settingsPages = ['General', 'Appearance', 'Proxy', 'Certificate', 'API defaults', 'Notifications', 'Storage', 'Shortcuts', 'Help', 'Integrations'] as const;
export type SettingsPage = typeof settingsPages[number];
export function SettingsCenter({ initial, onClose, flash, motion, onMotion, integrationTab }: { initial: SettingsPage; onClose: () => void; flash: (m: string) => void; motion: boolean; onMotion: () => void; integrationTab?:string }) {
  const [page, setPage] = useState(initial);
  const [prefs, save] = usePreferences();
  const [draft, setDraft] = useState(prefs);
  const [platform, setPlatform] = useState('Windows');
  const [scenario, setScenario] = useState('Unknown');
  const [error, setError] = useState('');
  const [storage, setStorage] = useState(() => Object.keys(localStorage).filter(k => k.startsWith('traffic-studio-')));
  const root = useRef<HTMLDivElement>(null);
  useDialogFocus(root,onClose);
  function update(patch: Partial<Preferences>) { setDraft(d => ({ ...d, ...patch })); setError(''); }
  function proxy(patch: Partial<Preferences['proxy']>) { update({ proxy: { ...draft.proxy, ...patch } }); }
  function apply() {
    if (!draft.proxy.host.trim() || !Number.isInteger(draft.proxy.port) || draft.proxy.port < 1 || draft.proxy.port > 65535) { setError('Enter a host and an integer port between 1 and 65535.'); setPage('Proxy'); return; }
    if (draft.proxy.upstream && !/^https?:\/\/[^\s:@]+(?::\d+)?$/i.test(draft.proxy.upstream)) { setError('Upstream must be http(s)://host[:port], without credentials.'); setPage('Proxy'); return; }
    if (!Number.isFinite(draft.api.timeout) || draft.api.timeout < 100 || draft.api.timeout > 120000) { setError('Timeout must be between 100 and 120000 ms.'); setPage('API defaults'); return; }
    save(draft); flash('Preferences saved locally. Network configuration remains a preview.');
  }
  return <div className="settings-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div ref={root} className="settings-center" role="dialog" aria-modal="true" aria-labelledby="settings-heading">
    <header><div><span className="eyebrow">LOCAL PREFERENCES · MOCK NETWORK CONFIGURATION</span><h2 id="settings-heading">Settings</h2></div><button aria-label="Close settings" onClick={onClose}><X size={18}/></button></header>
    <div className="settings-content"><nav aria-label="Settings sections">{settingsPages.map(item => <button key={item} aria-current={page === item ? 'page' : undefined} onClick={() => setPage(item)}>{item}</button>)}</nav><main><h3>{page}</h3>
      {page === 'General' && <><button onClick={()=>{onClose();window.dispatchEvent(new Event('traffic-studio-workspaces'));}}>Manage workspaces</button><p>Windows desktop preview. Work stays in this browser profile; no account, telemetry or background network service.</p><div className="settings-status">Runtime: MOCK · Proxy: disconnected · Storage: browser</div><label>Capture mock scenario<select value={draft.captureScenario} onChange={e=>update({captureScenario:e.target.value as Preferences['captureScenario']})}><option>Success</option><option>Failure</option></select></label><label>Sample retention plan (days)<input type="number" min={1} max={365} value={draft.retention} onChange={e => update({ retention: Math.min(365, Math.max(1, Number(e.target.value))) })}/></label><p>Retention is a configuration draft. Samples are never deleted automatically.</p><button onClick={() => { setDraft(defaults); setError('Defaults loaded into the draft. Apply to save.'); }}>Load preference defaults</button></>}
      {page === 'Appearance' && <><Personalization draft={draft} onChange={update}/><label>Theme<select value={draft.theme} onChange={e => update({ theme: e.target.value as Preferences['theme'] })}><option value="dark">Mine Shaft dark</option><option value="light">Light</option></select></label><label>Accent<input type="color" value={draft.accent} onChange={e => update({ accent: e.target.value })}/></label><label>Traffic row density<select value={draft.density} onChange={e => update({ density: e.target.value as Preferences['density'] })}><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select></label><label>Interface zoom<select value={draft.zoom} onChange={e => update({ zoom: Number(e.target.value) })}>{[80,90,100,110,125].map(v => <option key={v} value={v}>{v}%</option>)}</select></label><label><input type="checkbox" checked={draft.toolbar} onChange={e => update({ toolbar: e.target.checked })}/> Show capture toolbar</label><label><input type="checkbox" checked={draft.statusbar} onChange={e => update({ statusbar: e.target.checked })}/> Show status bar</label><label><input type="checkbox" checked={motion} onChange={onMotion}/> Animations (applies immediately)</label></>}
      {page === 'Proxy' && <><div className="settings-status">NOT CONNECTED — no system proxy or listener is changed</div><label>Listen host<input value={draft.proxy.host} onChange={e => proxy({ host: e.target.value })}/></label><label>Port<input type="number" value={draft.proxy.port} onChange={e => proxy({ port: Number(e.target.value) })}/></label><label>Protocol<select value={draft.proxy.mode} onChange={e => proxy({ mode: e.target.value })}>{['HTTP / HTTPS','SOCKS5','HTTP + SOCKS5'].map(v => <option key={v}>{v}</option>)}</select></label>{(['system','override','loopback','upstreamEnabled'] as const).map(k => <label key={k}><input type="checkbox" checked={draft.proxy[k]} onChange={e => proxy({ [k]: e.target.checked })}/>{{ system: 'System proxy (planned)', override: 'Auto override (planned)', loopback: 'Allow loopback (planned)', upstreamEnabled: 'Use upstream (planned)' }[k]}</label>)}<label>Bypass patterns<textarea value={draft.proxy.bypass} onChange={e => proxy({ bypass: e.target.value })}/></label><label>Upstream URL (no credentials)<input placeholder="http://127.0.0.1:8080" value={draft.proxy.upstream} onChange={e => proxy({ upstream: e.target.value })}/></label><button disabled title="Requires native bridge">Apply to Windows</button><p>Rollback: this preview changes no Windows settings. In a native build, stop the listener and restore your previous Windows proxy configuration.</p></>}
      {page === 'Certificate' && <><div className="settings-status">Actual trust status: UNKNOWN · Fingerprint: unavailable</div><label>Preview state<select value={scenario} onChange={e => setScenario(e.target.value)}>{['Unknown','Not installed','Installed (simulation)','Error (simulation)'].map(v => <option key={v}>{v}</option>)}</select></label><p role="status">{scenario === 'Error (simulation)' ? 'Simulated error: certificate manager unavailable. Retry requires the native bridge.' : `Preview scenario: ${scenario}. This does not describe your OS trust store.`}</p><label>Platform<select value={platform} onChange={e => setPlatform(e.target.value)}>{['Windows','Firefox','Android','iOS','Java'].map(v => <option key={v}>{v}</option>)}</select></label><p>{platform} setup preview: obtain the CA from the future local certificate manager, inspect its fingerprint, and import it into the platform trust store. Follow platform documentation when the native manager is available.</p><label>SSL proxying URL patterns<textarea value={draft.proxy.sslPatterns} onChange={e => proxy({ sslPatterns: e.target.value })}/></label><button disabled>Install CA</button> <button disabled>Remove CA</button><p>Rollback preview: remove only the Traffic Studio certificate by its verified fingerprint. This build installs no certificate.</p></>}
      {page === 'API defaults' && <><label>Default timeout (ms)<input type="number" min={100} max={120000} value={draft.api.timeout} onChange={e => update({ api: { ...draft.api, timeout: Number(e.target.value) } })}/></label><label><input type="checkbox" checked={draft.api.redirects} onChange={e => update({ api: { ...draft.api, redirects: e.target.checked } })}/> Follow redirects by default</label><label><input type="checkbox" checked={draft.api.tls} onChange={e => update({ api: { ...draft.api, tls: e.target.checked } })}/> Verify TLS (configuration only)</label><p>Defaults apply to new drafts. Mock responses do not use network settings.</p></>}
      {page === 'Notifications' && <><label><input type="checkbox" checked={draft.toastEnabled} onChange={e => update({ toastEnabled: e.target.checked })}/> Show in-app toasts</label><label>Toast duration<select value={draft.toastSeconds} onChange={e => update({ toastSeconds: Number(e.target.value) })}>{[2,4,6,10].map(v => <option key={v} value={v}>{v} seconds</option>)}</select></label><button onClick={() => flash('Test notification — local preview.')}>Send test notification</button><p>Notification history lasts for this app session. No Windows push notification or background monitor is started.</p></>}
      {page === 'Storage' && <><p>{storage.length} Traffic Studio local entries. Auth values and credential headers are excluded from API saves; body and notes can still contain private data.</p><div className="storage-list">{storage.map(key => <div key={key}><span>{key.replace('traffic-studio-', '')}</span><small>{new Blob([localStorage.getItem(key) ?? '']).size} bytes</small></div>)}</div><button onClick={()=>{const data=Object.fromEntries(storage.map(k=>[k,localStorage.getItem(k)]));const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,entries:data},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='traffic-studio-local-backup.json';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export browser backup</button><button onClick={() => { setStorage(Object.keys(localStorage).filter(k => k.startsWith('traffic-studio-'))); flash('Local storage inventory refreshed.'); }}>Refresh inventory</button><p>Recovery: reload reopens browser drafts. Copy important content before clearing site data. The JSON backup is a local export; restore through each feature's validated import. Automatic recovery and SQLite/file storage require the native bridge.</p></>}
      {page === 'Shortcuts' && <dl>{[['Ctrl+T','New HTTP draft'],['Ctrl+W','Close API tab'],['Ctrl+Shift+T','Reopen closed tab'],['Ctrl+Tab','Next tab'],['Ctrl+G','Mock capture toggle'],['Ctrl+K','Traffic search'],['F1–F6','Context sidebar'],['Esc','Close dialog or menu']].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}
      {page === 'Help' && <><h4>Traffic Studio 0.1.0 Preview</h4><p>Sample traffic and API responses are simulated. Toolbox transforms and browser draft editing run locally.</p><h4>Changelog</h4><ul><li>Context sidebars, keyboard menus and persistent API tabs.</li><li>Request/response inspector, windowed traffic table.</li><li>Settings, mock network configuration, notifications and named layouts.</li></ul><h4>Troubleshooting</h4><p>If the screen is empty, load Sample Traffic or create an API request. A disconnected engine is expected. Browser storage must remain enabled to keep drafts.</p><button disabled title="No update channel configured">Check updates</button> <button disabled title="No feedback service configured">Send feedback</button></>}
      {page === 'Integrations' && <IntegrationDrafts initial={integrationTab}/>}
    </main></div><footer>{error && <span role="alert">{error}</span>}<button onClick={() => { setDraft(prefs); setError(''); }}>Discard edits</button><button onClick={apply}>Apply locally</button><button onClick={onClose}>Close</button></footer>
  </div></div>;
}
