import { UiText } from '../localization';
import { useState } from 'react';
import { listFlows } from '../../bridge/mockBridge';
import { useLocalDraft } from '../../views/useLocalDraft';
import { PageHead, DemoNote } from '../../shell/PageChrome';
import { SelectField } from '../../shell/SelectField';
import { Button } from '../../shell/Button';
import './analytics.css';
export function AnalyticsView({ onInspectHost }: { onInspectHost: (host: string) => void }) {
  const [host, setHost] = useState('All'); const [status, setStatus] = useState('All'); const [name, setName] = useState('');
  const [saved, setSaved] = useLocalDraft<{ name: string; host: string; status: string }[]>('traffic-studio-dashboards-v1', []);
  const all = listFlows(); const flows = all.filter(f => (host === 'All' || f.host === host) && (status === 'All' || String(f.status).startsWith(status)));
  const hosts = Array.from(new Set(all.map(f => f.host))); const duration = flows.map(f => f.duration).sort((a,b) => a-b);
  const metrics = [['Requests',flows.length],['Average latency',flows.length ? `${Math.round(duration.reduce((a,b) => a+b,0)/flows.length)} ms` : '—'],['P95 latency',flows.length ? `${duration[Math.max(0,Math.ceil(duration.length*.95)-1)]} ms` : '—'],['Error rate',flows.length ? `${Math.round(flows.filter(f => f.status>=400).length/flows.length*100)}%` : '—']];
  return <div className="workspace-page analytics-view"><PageHead kicker="SAMPLE TRAFFIC ANALYTICS" title="Analytics" description="Metrics, status distribution and host latency computed from sample flows."/><div className="page-toolbar"><label>Host <SelectField label="Analytics host" value={host} onChange={setHost} options={['All',...hosts].map(value=>({value,label:value}))}/></label><label><UiText text={"Status"}/> <SelectField label="Analytics status" value={status} onChange={setStatus} options={['All','2','3','4','5'].map(value=>({value,label:value==='All'?value:`${value}xx`}))}/></label><input aria-label="Dashboard name" placeholder="Dashboard name" value={name} onChange={e => setName(e.target.value)}/><Button disabled={!name.trim() || saved.some(v => v.name === name.trim())} onClick={() => { setSaved([...saved,{ name:name.trim(),host,status }]); setName(''); }}>Save dashboard</Button></div><div className="page-toolbar">{saved.map(v => <span key={v.name}><Button size="sm" onClick={() => { setHost(v.host); setStatus(v.status); }}>{v.name}</Button><Button variant="ghost" size="sm" aria-label={`Delete dashboard ${v.name}`} onClick={() => setSaved(saved.filter(i => i.name !== v.name))}>×</Button></span>)}</div>
<div className="metric-grid">{metrics.map(([label,value]) => <div className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>SAMPLE</small></div>)}</div>{flows.length ? <div className="analytics-grid"><div className="chart-panel"><h2>Status distribution</h2>{['2','3','4','5'].map(v => { const count = flows.filter(f => String(f.status).startsWith(v)).length; return <div key={v}><div className="status-chart-label"><span>{v}xx</span><strong>{count}</strong></div><div className="status-track"><span className="mint" style={{ width:`${count/flows.length*100}%` }}/></div></div>; })}</div><div className="chart-panel"><h2>Host latency · drill down</h2>{Array.from(new Set(flows.map(f => f.host))).map(h => { const matches = flows.filter(f => f.host === h); const avg = Math.round(matches.reduce((n,f) => n+f.duration,0)/matches.length); return <button className="host-row" key={h} onClick={() => onInspectHost(h)}><span>{h}</span><strong>{matches.length} requests · {avg} ms</strong></button>; })}</div></div> : <p className="no-results">No sample flows match. <button onClick={() => { setHost('All'); setStatus('All'); }}>Clear filters</button></p>}<DemoNote>Dashboards persist locally. All measurements are synthetic; no live session is analyzed.</DemoNote></div>;
}
