import { useEffect,useRef,useState } from 'react';
import { bridge,bridgeError } from '../../bridge';
import type { StoredEntity } from '../../domain/workspace';
import { VariableEditor } from './VariableEditor';
import { Button } from '../../shell/Button';
import { type Variable } from './resolution';
import { object,list,text,variables as importVariables } from '../api/adapters/common';
export function NativeEnvironmentPanel({workspaceId,onChange}:{workspaceId:string;onChange:(variables:Variable[])=>void}){
  const [rows,setRows]=useState<StoredEntity[]>([]);const [selected,setSelected]=useState<StoredEntity|null>(null);const [name,setName]=useState('New native environment');const [variables,setVariables]=useState<Variable[]>([]);const [input,setInput]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);
  const generation=useRef(0),callback=useRef(onChange);callback.current=onChange;
  useEffect(()=>{generation.current++;setRows([]);setSelected(null);setName('New native environment');setVariables([]);setDirty(false);setMessage('');setBusy(false);callback.current([]);return()=>{generation.current++;};},[workspaceId]);
  async function action(run:(operation:number)=>Promise<void>){const operation=generation.current;setBusy(true);setMessage('');try{await run(operation);}catch(e){if(generation.current===operation)setMessage(bridgeError(e).message);}finally{if(generation.current===operation)setBusy(false);}}
  function edit(next:Variable[]){setVariables(next);setDirty(true);callback.current(next);}
  async function refresh(operation:number){const next=await bridge.command('entity_query',{workspaceId,kind:'environment',limit:200,offset:0});if(generation.current===operation)setRows(next);}
  async function load(row:StoredEntity,operation:number){if(dirty&&!window.confirm('Discard unsaved native environment edits?'))return;const record=await bridge.command('environment_load',{workspaceId,id:row.id});const values=record.payload.variables;if(!Array.isArray(values)||values.some(value=>!value||typeof value!=='object'||Array.isArray(value)||typeof value.key!=='string'||typeof value.value!=='string'||typeof value.secret!=='boolean'))throw Error('Native environment rows are invalid.');const next=values.map(value=>{const row=value as unknown as Variable;return{key:row.key,value:row.value,secret:row.secret};});if(generation.current===operation){setSelected(record);setName(record.name);setVariables(next);setDirty(false);callback.current(next);}}
  async function save(operation:number){const record=await bridge.command('environment_save',{input:{workspaceId,id:selected?.id??crypto.randomUUID(),name,expectedRevision:selected?.revision??0,variables}});if(generation.current===operation){setSelected(record);setDirty(false);setMessage('Native environment saved. Secret values are protected in the Windows vault; SQLite environment metadata contains references only.');await refresh(operation);}}
  function importPostman(){try{if(input.length>1024*1024)throw Error('Environment import exceeds 1 MiB.');const raw=object(JSON.parse(input),'Postman environment');if(raw._postman_variable_scope!=='environment')throw Error('Expected a Postman environment JSON export.');const next=importVariables(list(raw.values,'environment values',1000).filter(value=>object(value).enabled!==false));setSelected(null);setName(text(raw.name,'Imported environment').slice(0,80));edit(next);setMessage('Environment converted into an unsaved draft. Disabled rows excluded; secret values removed. Review and Save to commit.');}catch(e){setMessage(bridgeError(e).message);}}
  return <details className="native-environments"><summary>Native environment variables</summary><p>Workspace SQLite environments. Secret values save to the Windows-user DPAPI vault and are decrypted only by explicit Load. Selected variables override browser environment values for this request. Save commits only when pressed.</p>
    <Button size="sm" disabled={busy||!workspaceId} onClick={()=>void action(refresh)}>Load native environments</Button><Button size="sm" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved native environment edits?'))return;setSelected(null);setName('New native environment');setDirty(false);setVariables([]);callback.current([]);}}>Clear selection / New</Button>
    {rows.map(row=><Button variant="ghost" size="sm" disabled={busy} key={row.id} onClick={()=>void action(op=>load(row,op))}>{row.name} · r{row.revision}</Button>)}
    <label>Environment name<input disabled={busy} value={name} onChange={e=>{setName(e.target.value);setDirty(true);}}/></label><fieldset disabled={busy} style={{border:0,padding:0}}><VariableEditor label="Native environment variable" rows={variables} onChange={edit}/></fieldset>
    <Button size="sm" disabled={busy||!workspaceId||!name.trim()} onClick={()=>void action(save)}>Save native environment</Button><textarea aria-label="Postman environment JSON" disabled={busy} value={input} onChange={e=>setInput(e.target.value)}/><Button size="sm" disabled={busy||!input} onClick={importPostman}>Preview Postman environment as draft</Button><p role="status">{message}</p>
  </details>;
}
